## Reading and writing files

numpy has many function to read and write files from/to disk.

In [6]:
import numpy as np

### Single array, binary format

In [7]:
a = np.random.rand(20)
a

array([ 0.75287106,  0.73332718,  0.04879838,  0.01142314,  0.16506819,
        0.27967917,  0.19660274,  0.23745617,  0.90701215,  0.67245764,
        0.41669475,  0.27148569,  0.14981605,  0.49759713,  0.41028837,
        0.45309543,  0.47942889,  0.07042276,  0.36087148,  0.96043798])

Save the array to a binary file named `a.npy`:

In [8]:
np.save('a', a)

In [9]:
ls

01_nparrays.ipynb  03_random.ipynb    05_plotting.ipynb
02_files.ipynb     04_fft.ipynb       a.npy


Load the array back into memory:

In [10]:
a_copy = np.load('a.npy')

In [11]:
a_copy

array([ 0.75287106,  0.73332718,  0.04879838,  0.01142314,  0.16506819,
        0.27967917,  0.19660274,  0.23745617,  0.90701215,  0.67245764,
        0.41669475,  0.27148569,  0.14981605,  0.49759713,  0.41028837,
        0.45309543,  0.47942889,  0.07042276,  0.36087148,  0.96043798])

### Single array, text format

In [12]:
b = np.random.randint(0, 10, (5,3))
b

array([[0, 1, 1],
       [5, 9, 4],
       [6, 9, 0],
       [0, 7, 2],
       [8, 7, 9]])

The `savetxt` function saves arrays in a simple, textual format that is less effecient, but easier for other languges to read:

In [19]:
np.savetxt('b.txt', b)

In [20]:
ls

01_nparrays.ipynb  03_random.ipynb    05_plotting.ipynb  b.txt
02_files.ipynb     04_fft.ipynb       a.npy


Using `%pycat` to look at the contents shows that the files is indeed a plain text file:

In [21]:
%pycat b.txt

0.000000000000000000e+00 1.000000000000000000e+00 1.000000000000000000e+00
5.000000000000000000e+00 9.000000000000000000e+00 4.000000000000000000e+00
6.000000000000000000e+00 9.000000000000000000e+00 0.000000000000000000e+00
0.000000000000000000e+00 7.000000000000000000e+00 2.000000000000000000e+00
8.000000000000000000e+00 7.000000000000000000e+00 9.000000000000000000e+00


In [22]:
np.loadtxt('b.txt')

array([[ 0.,  1.,  1.],
       [ 5.,  9.,  4.],
       [ 6.,  9.,  0.],
       [ 0.,  7.,  2.],
       [ 8.,  7.,  9.]])